### ISSUE TITLE
Problem on Raspberry

### ISSUE THREAD

**Issue by KataPi** [bitrate16/ppa6-python#3]
Hello,
I am using @eliasweingaertner 's script on raspberry. I'm not a programmer...
I am running the script through a nodejs server which creates a png and sends it to print.
Both the old script (without svg support) and the new one (with svg support) works well.

I would like to integrate the script directly into my nodejs ( [as issue](https://github.com/eliasweingaertner/peripage-A6-bluetooth/issues/5) ) but, for now, I just call it.

I installed your package with dependencies, on raspberry it can be installed only via pip3 command.
(Maybe an error in info [hcitools](https://github.com/bitrate16/ppa6-python#identify-printer-bluetooth-mac-address) + scan) 

It doesn't work for me. I also tried pairing the printer from the desktop.
```
Traceback (most recent call last):
  File "<string>", line 3, in connect
_bluetooth.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/bin/ppa6", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/ppa6/__main__.py", line 39, in main
    printer.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/ppa6/__init__.py", line 94, in connect
    self.sock.connect((self.mac, 1))
  File "<string>", line 5, in connect
bluetooth.btcommon.BluetoothError: timed out
```
what am I doing wrong?
Thank you
Andrew

**Comment by bitrate16** [comment]
Can you please tell me which version of raspberry pi do you have?
Later, i will perform some tests on RPi4 and RPi Zero and suggest a fix.

**Comment by KataPi** [comment]
Rpi 3

**Comment by miaiam** [comment]
I'm having the same error on my raspberry pi 3. 
It works without any errors when I remove the line "self.sock.settimeout(self.timeout)" in the __init__.py file in the connect function (line 93). But I don't understand what the issue is and why it works when the line is removed

**Comment by bitrate16** [comment]
> It works without any errors when I remove the line "self.sock.settimeout(self.timeout)" in the **init**.py file in the connect function (line 93). But I don't understand what the issue is and why it works when the line is removed

This issue may get fixed by commenting out the line of code because of the bluetooth service/device manually configures timeout and may not support settimeout. But anyway, i need to check it.

You can change the timeout by specifying it in the constructor like in this python sample:
```
import ppa6
printer = ppa6.Printer('MAC', ppa6.PrinterType. your printer type A6 or A6p, timeout=10.0)
printer.connect()
printer.printASCII('Hello')
printer.disconnect()
```
And check if it still fails to connect. This sample will set timeout to 10 seconds and attempt to connect and print a text.
If the problem persists, i'll check some docs about PyBluez on RPi3

**Comment by KataPi** [comment]
```
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ppa6
>>> printer = ppa6.Printer('xxxx', ppa6.PrinterType.A6, timeout=10.0)
>>> printer.connect()
Traceback (most recent call last):
  File "<string>", line 3, in connect
_bluetooth.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/ppa6-python/ppa6/__init__.py", line 94, in connect
    self.sock.connect((self.mac, 1))
  File "<string>", line 5, in connect
bluetooth.btcommon.BluetoothError: timed out
>>> 

```
I also tried to edit the file via nano: error ...

**Comment by KataPi** [comment]
from [this](https://raspberrypi.stackexchange.com/questions/121216/how-to-best-handle-raspberry-pi-4-and-smartphone-connection-over-bluetooth-and-p):

`sudo nano /etc/bluetooth/main.conf`

Un-comment both lines:

`discoverabletimeout=0 `

and

`pairabletimeout=0 `

same error...

**Comment by KataPi** [comment]
It works for me.
in the same shell i tried to load your script too and i got a new error ... maybe that's normal.
I don't know if it will be useful ....
```
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> import bluetooth
>>> sock = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
>>> sock.connect(('xxxx', 1))
>>> sock.settimeout(10.0)
>>> sock.close()
>>> 
>>> import ppa6
>>> printer = ppa6.Printer('xxxx', ppa6.PrinterType.A6, timeout=10.0)
>>> printer.connect()
Traceback (most recent call last):
  File "<string>", line 3, in connect
_bluetooth.error: (77, 'File descriptor in bad state')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/ppa6/__init__.py", line 94, in connect
    self.sock.connect((self.mac, 1))
  File "<string>", line 5, in connect
bluetooth.btcommon.BluetoothError: [Errno 77] File descriptor in bad state
>>>
``` 

If I first set .settimeout and then connect I get an error

```
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> import bluetooth
>>> sock = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
>>> sock.settimeout(10.0)
>>> sock.connect(('xxxx', 1))
Traceback (most recent call last):
  File "<string>", line 3, in connect
_bluetooth.error: (77, 'File descriptor in bad state')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 5, in connect
bluetooth.btcommon.BluetoothError: [Errno 77] File descriptor in bad state
>>> 
```

**Comment by bitrate16** [comment]
> in the same shell i tried to load your script too and i got a new error ... maybe that's normal.

It's normal because fixed code is not committed yet. As i see, the problem is caused by calling `.settimeout` before `.connect` which puts socket in the invalid state, so i will push a test fix

**Comment by hvfrancesco** [comment]
I'm experiencing the same issue on my Ubuntu 20.04 laptop, waiting to test the fix

**Comment by bitrate16** [comment]
@KataPi @hvfrancesco 
Pushed the test fix
Try to install it with

```
git clone https://github.com/bitrate16/ppa6-python
cd ppa6-python
pip install . --user
```

**Comment by KataPi** [comment]
Hi Bitrate16,
Now it works for me.
It print but poor quality... Jerky print

This is Elias script
![IMG_20210413_181207](https://user-images.githubusercontent.com/17763702/114586521-0c8bbd00-9c85-11eb-86d1-0d69be9e9c91.jpg)

This is yours
![IMG_20210413_181220](https://user-images.githubusercontent.com/17763702/114586720-40ff7900-9c85-11eb-91b4-2ad8f7bbe8ab.jpg)

This is the original
![0](https://user-images.githubusercontent.com/17763702/114586819-5674a300-9c85-11eb-8bcb-aa1776091620.jpg)

**Comment by bitrate16** [comment]
@KataPi 
You can try to change the print concentration using `-c 1`
```
python -m ppa6 -m <MAC> -c 1 -p <A6p or A6> -i image.png
```
And you will get almost the same print result

**Comment by hvfrancesco** [comment]
the fix works perfectly, thanks (default timeout is a bit short and sometimes does raise an issue, but as you can change it at instantiation or afterwards is perfectly ok). great work!

**Comment by KataPi** [comment]
Hello,
Sorry for the delay.
I tried the -c1 command but the quality is still low.
The noise is also not smooth but feels jerky.
Does it only happen to me?

![IMG_20210415_132758](https://user-images.githubusercontent.com/17763702/114862882-5b556600-9def-11eb-9ff0-1240c5fc48e6.jpg)

**Comment by bitrate16** [comment]
@KataPi i'll look over this issue, but later
